
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Retrowarden.Dialogs {
    using Terminal.Gui;
    
    
    public partial class CreateSendDialog {
        
        public CreateSendDialog() {
            InitializeComponent();
        }
    }
}
