using System.ComponentModel;
using System.Data;
using System.Text;
using Terminal.Gui;
using Terminal.Gui.Trees;
using Retrowarden.Dialogs;
using Retrowarden.Models;
using Retrowarden.Utils;

//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Retrowarden.Views 
{
    public partial class MainView 
    {
        // Vault proxy reference.
        private VaultProxy _vaultProxy;
        private SortedDictionary<string, VaultItem> _vaultItems;
        private List<VaultFolder> _folders;
        private List<VaultCollection> _collections;
        private StringBuilder _aboutMessage;
        
        // Used for all long running operation indicators.
        private BackgroundWorker _worker;
        
        public MainView() 
        {
            // Initialize Application Stack
            Application.Init();
        
            // Initialize vault proxy.
            _vaultProxy = new VaultProxy();
            
            // Create about message.
            CreateAboutMessageASCII();
            
            // Setup screen controls.
            InitializeComponent();

            // Run the application loop.
            Application.Run(this);
        }

        private void CreateAboutMessageASCII()
        {
            _aboutMessage = new StringBuilder ();
            _aboutMessage.AppendLine (@"A terminal.gui based client for Bitwarden");
            _aboutMessage.AppendLine (@"");			
            _aboutMessage.AppendLine (@"______     _                                  _            ");
            _aboutMessage.AppendLine (@"| ___ \   | |                                | |           ");
            _aboutMessage.AppendLine (@"| |_/ /___| |_ _ __ _____      ____ _ _ __ __| | ___ _ __  ");
            _aboutMessage.AppendLine (@"|    // _ \ __| '__/ _ \ \ /\ / / _` | '__/ _` |/ _ \ '_ \ ");
            _aboutMessage.AppendLine (@"| |\ \  __/ |_| | | (_) \ V  V / (_| | | | (_| |  __/ | | |");
            _aboutMessage.AppendLine (@"\_| \_\___|\__|_|  \___/ \_/\_/ \__,_|_|  \__,_|\___|_| |_|");
            _aboutMessage.AppendLine (@""); 
        }

        #region UI Control Helpers
        private void LoadItemTableView(SortedDictionary<string, VaultItem> items)
        {
            // Create data table.
            DataTable itemTable = new DataTable();
            
            // Hide the "Id" column.
            TableView.ColumnStyle style = new TableView.ColumnStyle();
            style.Visible = false;
            DataColumn id = itemTable.Columns.Add("Id");
            
            // Add this column to table.
            this.tabItems.Style.ColumnStyles.Add(id, style);
            
            // Add visible columns.
            itemTable.Columns.Add("Site Name");
            itemTable.Columns.Add("User Id");
            
            // Loop through vault items.
            foreach (VaultItem item in items.Values)
            {
                // Create data row.
                DataRow row = itemTable.NewRow();
                
                // Set column data.
                row["Id"] = item.Id;
                row["Site Name"] = item.ItemName;
                row["User Id"] = item.Login.UserName;
                
                // Add row to table view.
                itemTable.Rows.Add(row);
            }
            
            // Set data source.
            this.tabItems.Table = itemTable;
        }

        private void LoadTreeView()
        {
            // Create root node.
            TreeNode root = new TreeNode("Bitwarden");
            root.Tag = new Tuple<NodeType, string>(NodeType.Root, null);
            
            // Create folders node.
            TreeNode folderNode = ViewUtils.CreateFoldersNode(_folders, _vaultItems);
            
            // Create collection node.
            TreeNode collectionNode = ViewUtils.CreateCollectionsNode(_collections, _vaultItems);
        
            // Create item nodes.
            TreeNode itemNodes = ViewUtils.CreateAllItemsNodes(_vaultItems);
        
            // Add nodes to root.
            root.Children.Add(itemNodes);
            root.Children.Add(folderNode);
            root.Children.Add(collectionNode);
        
            // Add nodes to control.
            this.tvwItems.AddObject(root);
        }
        
        private SortedDictionary<string, VaultItem> GetVaultItemsForTreeNode(ITreeNode node)
        {
            SortedDictionary<string, VaultItem> retVal = new SortedDictionary<string, VaultItem>();
            
            // Loop through child nodes.
            foreach (TreeNode child in node.Children)
            {
                // Get node tag.
                Tuple<NodeType, string> nodeData = (Tuple<NodeType, string>) child.Tag;
                
                // Check to see that the child node is a vault item.
                if (nodeData.Item1 == NodeType.Item)
                {
                    // Lookup node in item dictionary.
                    VaultItem item = _vaultItems[nodeData.Item2];
                
                    // Add to filtered list.
                    retVal.Add(item.Id, item);   
                }
            }
            
            // Return filtered list.
            return retVal;
        }

        private void ShowDetailForm(VaultItemDetailViewState state)
        {
            // Get the current item from tableview.
            DataRow selectedRow = tabItems.Table.Rows[tabItems.SelectedRow];
           
            // Get the item associated with this row.
            VaultItem item = _vaultItems[(string)selectedRow["Id"]];
           
            // Create item detail dialog.
            VaultItemDetailView detailView = new VaultItemDetailView(item, _folders, state);
            
            // Update title.
            switch (state)
            {
                case VaultItemDetailViewState.Create:
                    detailView.Title = "Create New Item";
                    break;
                
                case VaultItemDetailViewState.Edit:
                    detailView.Title = "Edit Item - " + item.ItemName;
                    break;
                
                case VaultItemDetailViewState.View:
                    detailView.Title = "View Item - " + item.ItemName;
                    break;
            }
            
            // Show the view modal.
            detailView.Show();

        }
        #endregion
        
        #region Proxy Workers
        private void RunLoginWorker(string userId, string password)
        {
            // Get background worker.
            _worker = new BackgroundWorker () { WorkerSupportsCancellation = true };
            
            // Create working dialog.
            WorkingDialog _workingDialog = new WorkingDialog("Logging in");
            
            // Run the login method.
            _worker.DoWork += (s, e) => 
            {
                // Execute the login method.
                 _vaultProxy.Login(userId, password);
            };
            
            // Add completion event handler.
            _worker.RunWorkerCompleted += (s, e) => 
            {   
                // Check to see if the dialog is present.
                if (_workingDialog.IsCurrentTop) 
                {
                    //Close the dialog
                    _workingDialog.Hide();
                }
                
                // Clear out the worker.
                _worker = null;
            };
            
            // Run the worker.
            _worker.RunWorkerAsync ();
            
            // Show working dialog.
            _workingDialog.Show();
        }
        
        private void RunLogoutWorker()
        {
            // Get background worker.
            _worker = new BackgroundWorker () { WorkerSupportsCancellation = true };
            
            // Create working dialog.
            WorkingDialog _workingDialog = new WorkingDialog("Logging out");
            
            // Run the fetch method.
            _worker.DoWork += (s, e) => 
            {
                // Try to logout.
                _vaultProxy.Logout();
            };

            // Add completion event handler.
            _worker.RunWorkerCompleted += (s, e) => 
            {   
                // Check to see if the dialog is present.
                if (_workingDialog.IsCurrentTop) 
                {
                    //Close the dialog
                    _workingDialog.Hide();
                }
                
                // Clear out the worker.
                _worker = null;
            };
            
            // Run the worker.
            _worker.RunWorkerAsync ();
            
            // Show working dialog.
            _workingDialog.Show();
        }
        
        private void RunGetItemsWorker()
        {
            // Get background worker.
            _worker = new BackgroundWorker () { WorkerSupportsCancellation = true };
            
            // Create working dialog.
            WorkingDialog _workingDialog = new WorkingDialog("Syncing Vault Items");
            
            // Run the fetch method.
            _worker.DoWork += (s, e) => 
            {
                // Try to fetch vault items.
                _vaultItems = _vaultProxy.ListVaultItems();
            };

            // Add completion event handler.
            _worker.RunWorkerCompleted += (s, e) => 
            {   
                // Check to see if the dialog is present.
                if (_workingDialog.IsCurrentTop) 
                {
                    //Close the dialog
                    _workingDialog.Hide();
                }
                
                // Clear out the worker.
                _worker = null;
            };
            
            // Run the worker.
            _worker.RunWorkerAsync ();
            
            // Show working dialog.
            _workingDialog.Show();
        }
        
        private void RunGetFoldersWorker()
        {
            // Get background worker.
            _worker = new BackgroundWorker () { WorkerSupportsCancellation = true };
            
            // Create working dialog.
            WorkingDialog _workingDialog = new WorkingDialog("Syncing Folders");
            
            // Run the fetch method.
            _worker.DoWork += (s, e) => 
            {
                // Get folders.
                _folders = _vaultProxy.ListFolders();
            };

            // Add completion event handler.
            _worker.RunWorkerCompleted += (s, e) => 
            {   
                // Check to see if the dialog is present.
                if (_workingDialog.IsCurrentTop) 
                {
                    //Close the dialog
                    _workingDialog.Hide();
                }
                
                // Clear out the worker.
                _worker = null;
            };
            
            // Run the worker.
            _worker.RunWorkerAsync ();
            
            // Show working dialog.
            _workingDialog.Show();
        }
        
        private void RunGetCollectionsWorker()
        {
            // Get background worker.
            _worker = new BackgroundWorker () { WorkerSupportsCancellation = true };
            
            // Create working dialog.
            WorkingDialog _workingDialog = new WorkingDialog("Syncing Collections");
            
            // Run the fetch method.
            _worker.DoWork += (s, e) => 
            {
                // Get collections.
                _collections = _vaultProxy.ListCollections();
            };

            // Add completion event handler.
            _worker.RunWorkerCompleted += (s, e) => 
            {   
                // Check to see if the dialog is present.
                if (_workingDialog.IsCurrentTop) 
                {
                    //Close the dialog
                    _workingDialog.Hide();
                }
                
                // Clear out the worker.
                _worker = null;
            };
            
            // Run the worker.
            _worker.RunWorkerAsync ();
            
            // Show working dialog.
            _workingDialog.Show();
        }
        #endregion
        
        #region Event Handlers
        private void HandleConnectionRequest()
        {
            ConnectDialog connectDialog = new ConnectDialog();

            connectDialog.Show();
            
            if (connectDialog.OkPressed)
            {
                // Run login worker and show working dialog.
                RunLoginWorker(connectDialog.UserId, connectDialog.Password);
                
                // Check to see if the login was successful.
                if (_vaultProxy.ExitCode == "0")
                {
                    // Run workers for items, folders, and collections.
                    RunGetItemsWorker();
                    
                    // Check to see if items were found.
                    if (_vaultProxy.ExitCode == "0")
                    {
                        // Run workers for folders and collections.
                        RunGetFoldersWorker();
                        RunGetCollectionsWorker();

                        LoadTreeView();
                        LoadItemTableView(_vaultItems);
                    }
                }

                else
                {
                    // Show error dialog.
                    MessageBox.ErrorQuery("Login failed.", _vaultProxy.ErrorMessage, "Ok");
                }
            }
        }

        private void HandleQuitRequest()
        {
            int response = MessageBox.Query("Confirm Action", "Quit.  Are you Sure?", "Ok", "Cancel");
            
            // Check to see if the user confirmed action.
            if (response == 0)
            {
                // Logout of vault.
                RunLogoutWorker();
                
                // Clear any clipboard contents.
                Clipboard.TrySetClipboardData("");
                
                // Close application.
                Application.RequestStop(this);
                Environment.Exit(Environment.ExitCode);
            }
        }

        private void HandleTreeviewSelectionChanged(object? sender, SelectionChangedEventArgs<ITreeNode> e)
        {
            // Get node that was selected.
            ITreeNode selected = e.NewValue;
            
            // Get the node data for this node.
            Tuple<NodeType, string> nodeData = (Tuple<NodeType, string>) selected.Tag;
            
            // Check to see if this node has children.
            if (nodeData.Item1 != NodeType.Item)
            {
                // Get the list of children.
                SortedDictionary<string, VaultItem> list = GetVaultItemsForTreeNode(selected);
                
                // Update tableview with scoped list.
                LoadItemTableView(list);
            }
        }
        
        private void HandleHelpKeypress()
        {
            Console.WriteLine("Help Fired");
        }

        private void HandleViewItemKeypress()
        {
            // Call helper method.
            ShowDetailForm(VaultItemDetailViewState.View);
        }
        
        private void HandleEditItemKeypress()
        {
            ShowDetailForm(VaultItemDetailViewState.Edit);
        }
        private void HandleUserCopyKeypress()
        {
            // Get the current item from tableview.
            DataRow selectedRow = tabItems.Table.Rows[tabItems.SelectedRow];
           
            // Get the item associated with this row.
            VaultItem item = _vaultItems[(string)selectedRow["Id"]];
            
            // Copy user name to clipboard.
            Clipboard.TrySetClipboardData(item.Login.UserName);
            
            // Indicate data copied.
            MessageBox.Query("Action Completed", "Username copied to clipboard.", "Ok");
        }
        
        private void HandlePwdCopyKeypress()
        {
            // Get the current item from tableview.
            DataRow selectedRow = tabItems.Table.Rows[tabItems.SelectedRow];
           
            // Get the item associated with this row.
            VaultItem item = _vaultItems[(string)selectedRow["Id"]];
            
            // Copy password to clipboard.
            Clipboard.TrySetClipboardData(item.Login.Password);

            // Indicate data copied.
            MessageBox.Query("Action Completed", "Password copied to clipboard.", "Ok");
        }
        
        private void HandleItemTableSelectedCellChanged(TableView.SelectedCellChangedEventArgs obj)
        {
            // Create new status bar items.
            StatusItem stiView = new StatusItem(Key.F2, "~F2~ - View Item", HandleViewItemKeypress);
            StatusItem stiEdit = new StatusItem(Key.F3, "~F3~ - Edit Item", HandleEditItemKeypress);
            StatusItem stiCopyUser = new StatusItem(Key.F4, "~F4~ - Copy UserName", HandleUserCopyKeypress);
            StatusItem stiCopyPwd = new StatusItem(Key.F5, "~F5~ - Copy Password", HandlePwdCopyKeypress);
            
            // Add them to the status bar.
            staMain.Items = new StatusItem[] { stiHelp, stiView, stiEdit, stiCopyUser, stiCopyPwd };
            
        }
        #endregion
    }
}
